import = ["~/.config/alacritty/themes/tokyo-night-moon.toml"]

[font]
normal = { family = "TX-02" }
size = 16.0

[window]
opacity = 0.90
blur = true
padding.x = 4
padding.y = 0

[cursor]
style = { shape = "Block", blinking = "Never" }

[terminal]
shell = { program = "/bin/zsh" }
