include themes/tokyo-night-moon.conf

font_family      TX-02
font_size        16.0

background_opacity 0.90
background_blur    32

cursor_shape           block
cursor_blink_interval  0

window_padding_width   0 4

shell_integration      no-cursor title

confirm_os_window_close 0
enable_audio_bell       no
